# ===================================================================
# CONFIGURA��ES DA APLICA��O
# ===================================================================
spring.application.name=controledegastos
server.port=${PORT:8090}
# ===================================================================
# CONEX�O COM BANCO DE DADOS (Neon.tech PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://ep-curly-unit-acbg893n-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_b9ImKlFw0ZTE
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURA��ES JPA / HIBERNATE
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURA��ES DO JWT
# ===================================================================
jwt.secret=9a2f8c4e7b1a5d3f8e6c4b2a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e
jwt.expiration=86400000
# Personaliza o caminho do Swagger UI (opcional, o padr�o � /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Personaliza o caminho da especifica��o OpenAPI em JSON
springdoc.api-docs.path=/v3/api-docs